# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Nonprod FTB environment to deploy to, i.e. test/int/int2/stage'
        required: true
        default: 'test'
      tags:
        description: 'Single tag or comma-separated list of tags for conduit files'
        required: true
        default: '1.0.1'
      dcr:
        description: 'Number of ABC ticket - i.e. ABC-1234'
        required: true
        default: 'ABC-1234'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: |
        docker image build -t cloudtechmasters/spring-boot-azure-micro-svc-sept19:v1 .
      
    - name: Docker Push
      run: |
        docker image push cloudtechmasters/spring-boot-azure-micro-svc-sept19:v1
    
